from dataclasses import dataclass
from datetime import datetime
from enum import Enum


class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass(frozen=True, slots=True)
class Signal:
    """
    Represents a trading signal generated by a strategy.
    """

    symbol: str
    signal_type: SignalType
    confidence: float
    timeframe: str
    strategy: str
    timestamp: datetime
    reason: str

    def __post_init__(self):
        """
        Validate signal values.
        """

        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("Confidence must be between 0.0 and 1.0.")

        if not self.symbol.strip():
            raise ValueError("Symbol cannot be empty.")

        if not self.strategy.strip():
            raise ValueError("Strategy name cannot be empty.")

        if not self.timeframe.strip():
            raise ValueError("Timeframe cannot be empty.")

        if not self.reason.strip():
            raise ValueError("Reason cannot be empty.")